### ISSUE TITLE
Thoughts about the future of this project with Tauri

### ISSUE THREAD

**Issue by amrbashir** [rust-mobile/xbuild#111]
Hi, I am Amr, a Core member of Tauri org. I have been aware of this project for a while, but I finally decided to try it out and see if this could be used by tauri-cli for mobile development. The project is well thought-out and was easy to use. Great job! I have been kinda dissatisfied with our [`cargo-mobile`](https://github.com/BrainiumLLC/cargo-mobile) fork ([tauri-mobile](https://github.com/tauri-apps/tauri-mobile)) for some time now and I hope we can use this project instead and join efforts to make mobile DX for rust apps better.

### Configuration
Right now, the configuration is written in `yaml` which is very hard to use and I don't think is very rusty over all, so why did you decide on `yaml`? why not use `toml` which is more rustic? actually why not reuse Cargo.toml? I think I'd prefer to have the configuration in Cargo.toml

```toml
[package]
name = "template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.68"
dioxus = "0.3.1"

[xbuild.android]
gradle = true
wry = true

[xbuild.ios]
# and so on

```

## Wry Special handling
I see that there is a toggle for wry specifically which is not dynamic at all and i think `xbuild` shouldn't care about special handling for wry, instead I think the template should have options to specify the needed changes to make wry work which IIRC is only some env vars, dependencies, theme parent, name of the default activity to launch. I think some of them could be already set by the configuration and some are not like env vars and I think the following solution is better than hard-coding them inside `xbuild`
```yaml
android:
  env_vars:
  	- WRY_ANDROID_LIBRARY: template
    - WRY_ANDROID_PACKAGE: com.example.template
    - WRY_ANDROID_KOTLIN_FILES_OUT_DIR: "<android-project-dir>/app/src/main/kotlin/com/example/template" # <gradle-dir> will be replaced by `xbuild` at runtime
```

### Gradle and Xcode projects
I saw that there is a kotlin directory in the generated template that I am assuming will host all my custom kotlin template (not sure if there is a similar one for iOS) but I don't think this is enough, at Tauri we recently merged the inital work for Android plugins where you can write your code in kotlin encapsulated in an Android project which you can invoke through Rust/JS see [here](https://github.com/tauri-apps/tauri/tree/next/examples/api/src-tauri/tauri-plugin-sample) for an example. 
With the current approach of `xbuild` (hiding gradle and xcode projects away) it makes it harder to modify the xcode/gradle projects to include these plugins in there and modify the gradle build script, even if `android.dependcies` in `manifest.yaml` could be enough to include this "tauri-plugins", it will still be harder for tauri users to include kotlin libraries or wildly modify the android project with modifications beyond the options provided by `xbuild`. I think the best way forward for this would be to bootstrap an `android` and `iOS` directories in the generated template (similar to how flutter project works), add some warning comments about stuff that shouldn't be modified or removed and leave everything else at the hands of users.

## Windows, macOS and Linux bundlers
I see that there is bundle options for various bundle formats for Windows, macOS and Linux which felt out of place since this a project that is under `rust-mobile` org so I thought it was only for mobile development. We at tauri we already have `tauri-bundler` to package `msi`, `nsis`, `dmg`, `dev`, `appimage` and `app` formats but I think we might want to extract it to its own CLI/Library which I think aligns with the same direction of this project as well so my question is will `xbuild` grow beyond just mobile and move to its own org or stay under rust-mobile umbrella? would it be acceptable to port some missing targets from `tauri-bundler` to `xbuild` instead?
