### ISSUE TITLE
how to configure

### ISSUE THREAD

**Issue by LuckyTurtleDev** [rust-mobile/xbuild#152]
How can I figure configure xbuild? For example to enable full screen mode.

**Comment by StratusFearMe21** [comment]
Hi! The missing docs in this project is definitely a problem, but here's how you do it. All the configuration is in `manifest.yaml` in the root of the project, and this is how you would set fullscreen mode in that
```yaml
android:
  gradle: true
  manifest:
    application:
      theme: "@android:style/Theme.NoTitleBar.Fullscreen"
```

You can find the structs that the `yaml` deserializes to [here](https://github.com/rust-mobile/xbuild/blob/master/xbuild/src/config.rs#L14)
